# Generated by Django 5.1.6 on 2025-02-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('content', models.TextField(blank=True, verbose_name='URL')),
                ('picture', models.ImageField(blank=True, upload_to='', verbose_name='картинка')),
            ],
        ),
    ]
