# Generated by Django 5.1.6 on 2025-02-14 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='content',
        ),
        migrations.AddField(
            model_name='donate',
            name='sum',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='сумма'),
            preserve_default=False,
        ),
    ]
