# Generated by Django 5.1.6 on 2025-02-08 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'категории'},
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('content', models.TextField(blank=True, verbose_name='контент')),
                ('picture', models.ImageField(blank=True, upload_to='', verbose_name='картинка')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'публикации',
                'unique_together': {('category', 'slug')},
            },
        ),
    ]
