# Generated by Django 5.1.6 on 2025-02-15 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'пост', 'verbose_name_plural': 'публикации'},
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('reaction', models.IntegerField(choices=[(1, 'Лайк'), (-1, 'Дизлайк')], verbose_name='реакция')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='публикация')),
            ],
            options={
                'verbose_name': 'лайк',
                'verbose_name_plural': 'реакции',
            },
        ),
    ]
