# Generated by Django 5.1.6 on 2025-02-14 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_donate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='комментарий')),
                ('date', models.DateTimeField(blank=True, verbose_name='дата')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='публикации')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comments', verbose_name='родитель')),
            ],
        ),
    ]
