# Generated by Django 5.1.6 on 2025-02-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('link', models.URLField(verbose_name='ссылка')),
                ('icon', models.ImageField(upload_to='', verbose_name='иконка')),
            ],
            options={
                'verbose_name': 'сервис',
                'verbose_name_plural': 'сервисы донатов',
            },
        ),
    ]
