# Generated by Django 5.1.6 on 2025-02-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donate',
        ),
        migrations.AlterField(
            model_name='likes',
            name='reaction',
            field=models.BooleanField(verbose_name='реакция'),
        ),
    ]
