# Generated by Django 5.1.6 on 2025-02-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_donat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('category', 'slug')},
        ),
    ]
